# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='app.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('type', models.CharField(choices=[('N', 'Number'), ('S', 'String'), ('B', 'Boolean'), ('E', 'Enum')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('condition_items', models.ManyToManyField(related_name='condition_in_requirements', to='app.ProcessItem')),
                ('intoruced_items', models.ManyToManyField(related_name='introduced_in_requirements', to='app.ProcessItem')),
                ('prevent_items', models.ManyToManyField(related_name='prevent_in_requirements', to='app.ProcessItem')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequirementCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('custom_value', models.CharField(blank=True, max_length=100, null=True)),
                ('condition_parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ProjectParameter')),
                ('parameter_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ParameterValue')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='app.ProjectRequirement')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='condition_items',
            field=models.ManyToManyField(related_name='condition_in_processes', to='app.ProcessItem'),
        ),
        migrations.AddField(
            model_name='process',
            name='prevent_items',
            field=models.ManyToManyField(related_name='prevent_in_processes', to='app.ProcessItem'),
        ),
        migrations.AddField(
            model_name='process',
            name='result_items',
            field=models.ManyToManyField(related_name='result_in_processes', to='app.ProcessItem'),
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='app.ProjectParameter'),
        ),
        migrations.AlterUniqueTogether(
            name='projectrequirementcondition',
            unique_together=set([('requirement', 'condition_parameter')]),
        ),
        migrations.AlterUniqueTogether(
            name='parametervalue',
            unique_together=set([('name', 'parameter')]),
        ),
    ]
