# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrequirementcondition',
            name='parameter_value',
        ),
        migrations.AddField(
            model_name='projectrequirementcondition',
            name='allowed_values',
            field=models.ManyToManyField(blank=True, to='app.ParameterValue'),
        ),
    ]
