# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170123_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrequirement',
            old_name='intoruced_items',
            new_name='introduced_items',
        ),
    ]
